{{- if .Values.neo4j.neo4j.passwordFromSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.neo4j.neo4j.passwordFromSecret }}
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}