apiVersion: v2
name: keycloak
description: Keycloak wrapper chart for AAS (includes realm import)
version: 0.10.0

dependencies:
  - name: keycloak
    version: 18.0.2
    repository: oci://registry-1.docker.io/bitnamicharts
