replicaCount: 2

image:
  repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/tsa
  name: signer
  tag: "v2.1.0"
  pullPolicy: Always
useConfigMap: false
configMapName: my-configmap
useSecretRef: false
secretRefName: my-secret
podAnnotations: {}
resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

metrics:
  enabled: true
  port: 2112

log:
  level: "debug"
  encoding: json

security:
  runAsNonRoot: false
  runAsUid: 0
  runAsGid: 0

service:
  port: 8080

signer:
  version: 0.26.0
  http:
    host: ""
    port: 8080
    timeout:
      idle: 120s
      read: 10s
      write: 10s
  nats:
    enabled: true
    natsHost: nats://nats.NAMESPACE.svc.cluster.local:4222
    topic: sign
  sdjwt:
    url: http://sd-jwt-service.NAMESPACE.svc.cluster.local:3000
  engine:
    image: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/tsa/crypto-provider-hashicorp-vault-plugin:v2.0.3
    address: 0.0.0.0:50051
    clusterAdress: 127.0.0.1:50051
    pullPolicy: Always
    env:
      VAULT_ADRESS: http://vault.NAMESPACE.svc.cluster.local:8200
    secretEnv:
      VAULT_TOKEN:
        name: vault
        key: token

ingress:
  enabled: false
istio:
  injection:
    pod: false

extraVars:
  - name: ENGINE_PATH
    value: "/opt/plugins/hashicorp-vault-provider.so"
  - name: VAULT_ADDR
    value: "http://vault.NAMESPACE.svc.cluster.local:8200"
  - name: VAULT_ADRESS
    value: "http://vault.NAMESPACE.svc.cluster.local:8200"
  - name: TRANSIT_MOUNT_PATH
    value: "transit"
  - name: TRANSIT_KEY_NAME
    value: "SDJWTCredential"
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        name: "vault"
        key: "token"
