pre-authorization-bridge:
  image: 
    pullPolicy: Always
    tag: "v2.2.1"
  ingress:
   enabled: true
   annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/cluster-issuer: letsencrypt-prod
   hosts:
     - host: cloud-wallet.DOMAIN
       paths:
         - path: /.well-known/openid-configuration
           pathtype: Exact
           port: 8080
         - path: /token
           pathtype: Exact
           port: 8080
   tls:
     - secretName: xfsc-wildcard
       hosts:
         - cloud-wallet.DOMAIN
  config:
    nats:
      url: nats.NAMESPACE.svc.cluster.local:4222
      queuegroup: preauth
      timeoutInSec: 10s
    logLevel: debug
    servingPort: 8080
    database:
      username: default
      password: pass
      hosts: redis-master.NAMESPACE.svc.cluster.local:6379
      port: 6379
      db: 0
      IsCluster: false
    oAuth:
      signerTopic: sign
      signerJwksUrl: http://signer.NAMESPACE.svc.cluster.local/v1/jwks
      credentialEndpoint: http://signer.NAMESPACE.svc.cluster.local/v1/credential
      key: signerkey
      namespace: NAMESPACE 
      groupid:
      issuerKid: "did:web:cloud-wallet.DOMAIN#signerkey"
    wellKnown:
      issuer: https://cloud-wallet.DOMAIN
      token_endpoint: https://cloud-wallet.DOMAIN/token
      jwks_uri: https://cloud-wallet.DOMAIN/.well-known/jwks.json
      grant_types_supported:
        - urn:ietf:params:oauth:grant-type:pre-authorized_code
