keycloak:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "3"
      memory: "4Gi"
  image:
    registry: docker.io
    repository: bitnamilegacy/keycloak
    tag: 26.3.2-debian-12-r0

  auth:
    adminUser: admin
    existingSecret: keycloak-init-secrets
    passwordSecretKey: "password"
    annotations: {}

  replicaCount: 1

  extraEnvVars:
    - name: KC_HOSTNAME
      value: https://key-server.DOMAIN
    - name: KC_PROXY_HEADERS
      value: xforwarded
    - name: KC_HTTP_ENABLED
      value: "true"

  containerPorts:
    http: 8080
    https: 8443
    infinispan: 7800

  tls:
    enabled: true
    usePem: true
    existingSecret: TLS_SECRET

  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: ImplementationSpecific
    hostname: key-server.DOMAIN
    path: "/"
    servicePort: http
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
      nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    tls: false
    extraTls:
      - hosts:
          - key-server.DOMAIN
        secretName: TLS_SECRET

  keycloakConfigCli:
    enabled: true
    existingConfigmap: gaia-x-realm-config
    image:
      registry: docker.io
      repository: bitnamilegacy/keycloak-config-cli
      tag: 6.4.0-debian-12-r11
    

  postgresql:
    enabled: true
    auth:
      username: keycloak
      database: keycloak
      existingSecret: keycloak-init-secrets
    architecture: standalone
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql