{{- if not .Values.externalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-auth-server-keys-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  iat: {{ .Values.secrets.keys.iat | quote }}
  jwk: {{ .Values.secrets.keys.jwk | quote }}
{{- end }}
